description: havok
env: test
logger:
  level: debug

plugin:
  path: .
  conf:
    fetchers:
      FileFetcher:
        file: ./local.log
        decoder:
          - Decoder

httpclient:
  keepalive: true
  timeout: 60000000000  # 60s
  dialtimeout: 30000000000  # 30s
  keepalivetimeout: 30000000000  # 30s
  maxidleconn: 2000
  maxidleconnperhost: 1000
  idleconntimeout: 30000000000  # 30s
  tlshandshaketimeout: 10000000000  # 10s
  expectcontinuetimeout: 1000000000  # 1s