name: Havok CI
on:
- push
- pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      name: Set up Go 1.18
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
      name: Check out code into Go module directory
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: 3.18.1
    - name: Run Unittest Cases
      run: make test
    - name: Code Coverage Report
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.txt
        verbose: true
        flags: unittest
        fail_ci_if_error: true